package cz.cuni.mff.odcleanstore.vocabulary;

/**
 * Vocabulary definitions of internal ODCleanStore URIs and URI prefixes.
 *
 * @author Jan Michelfeit
 */
public final class ODCSInternal {
    /** Prefix of URIs visible for public. */
    private static final String NS_PUBLIC = ODCS.getURI();
    
    /** Prefix of URIs for internal usage. */
    private static final String NS_INTERNAL = ODCS.getURI() + "internal/";

    /** Disable constructor for a utility class. */
    private ODCSInternal() {
    }

    /* Vocabulary properties: */

    // CHECKSTYLE:OFF

    /**
     * Temporary prefix for new graphs in clean database. 
     */
    public static final String hiddenGraphPrefix = NS_INTERNAL + "hiddenGraph/";
    /**
     * Temporary prefix for new graphs in clean database. Must start with {@link #hiddenGraphPrefix}!
     */
    public static final String newGraphPrefix = hiddenGraphPrefix + "newGraph/";
    
    /**
     * Temporary prefix for old graphs in clean database. Must start with {@link #hiddenGraphPrefix}!
     */
    public static final String oldGraphPrefix = hiddenGraphPrefix + "oldGraph/";
    
    /**
     * Infix of named graphs where incoming data are stored. 
     */
    public static final String dataGraphUriInfix = "data/";
    
    /**
     * Infix of named graphs where metadata about incoming named graphs are stored.
     */
    public static final String metadataGraphUriInfix = "metadata/";

    /**
     * Infix of named graphs where provenance metadata about incoming named graphs are stored.
     */
    public static final String provenanceMetadataGraphUriInfix = "provenanceMetadata/";
    
    /**
     * Prefix of named graphs where ontologies are stored.
     */
    public static final String ontologyGraphUriPrefix = NS_PUBLIC + "ontologies/";
    
    /**
     * Prefix of named graphs where ontology mappings are stored.
     */
    public static final String ontologyMappingsGraphUriPrefix = NS_INTERNAL + "ontologyMappings/";
    
    /**
     * Prefix for temporary graphs created for rule debugging
     */
    public static final String debugTempGraphUriPrefix = NS_INTERNAL + "debugTmp/";
    
    /**
     * Name of a graph to put aggregated score to. 
     */
    public static final String aggregatedPublisherScoreGraphUri = NS_INTERNAL + "aggregatedPublisherScore";
    
    /**
     * Prefix of named graphs where links generated by OI are placed.
     */
    public static final String generatedLinksGraphUriPrefix = NS_INTERNAL + "generatedLinks/";
    
    /**
     * Infix of named graph where metadata in the output are stored.
     */
    public static final String queryMetadataGraphUriInfix = "metadata/";
    
    /**
     * Infix of URIs identifying a Quality Assessment rule.
     */
    public static final String queryQARuleUriInfix = "QARule/";
    
    /**
     * Infix of URIs of named graph where the result quads are placed
     */
    public static final String queryResultGraphUriInfix = "results/";
    
    // CHECKSTYLE:ON
}
