package cz.cuni.mff.odcleanstore.vocabulary;


/**
 * Vocabulary definitions of internal ODCleanStore URIs and URI prefixes.
 *
 * @author Jan Michelfeit
 */
public final class ODCSInternal {
    /** The namespace of the vocabulary as a string. */
    public static final String NAMESPACE = ODCS.NAMESPACE + "internal/";
    
    /** Disable constructor for a utility class. */
    private ODCSInternal() {
    }

    /* Vocabulary properties: */
    /**
     * Temporary prefix for new graphs in clean database. 
     */
    public static final String HIDDEN_GRAPH_PREFIX = NAMESPACE + "hiddenGraph/";
    /**
     * Temporary prefix for new graphs in clean database. Must start with {@link #HIDDEN_GRAPH_PREFIX}!
     */
    public static final String NEW_GRAPH_PREFIX = HIDDEN_GRAPH_PREFIX + "newGraph/";
    
    /**
     * Temporary prefix for old graphs in clean database. Must start with {@link #HIDDEN_GRAPH_PREFIX}!
     */
    public static final String OLD_GRAPH_PREFIX = HIDDEN_GRAPH_PREFIX + "oldGraph/";
    
    /**
     * Infix of named graphs where incoming data are stored. 
     */
    public static final String DATA_GRAPH_URI_INFIX = "data/";
    
    /**
     * Infix of named graphs where metadata about incoming named graphs are stored.
     */
    public static final String METADATA_GRAPH_URI_INFIX = "metadata/";

    /**
     * Infix of named graphs where provenance metadata about incoming named graphs are stored.
     */
    public static final String PROVENANCE_METADATA_GRAPH_URI_INFIX = "provenanceMetadata/";
    
    /**
     * Prefix of named graphs where ontologies are stored.
     */
    public static final String ONTOLOGY_GRAPH_URI_PREFIX = ODCS.NAMESPACE + "ontologies/";
    
    /**
     * Prefix of named graphs where ontology mappings are stored.
     */
    public static final String ONTOLOGY_MAPPINGS_GRAPH_URI_PREFIX = NAMESPACE + "ontologyMappings/";
    
    /**
     * Prefix for temporary graphs created for rule debugging.
     */
    public static final String DEBUG_TEMP_GRAPH_URI_PREFIX = NAMESPACE + "debugTmp/";
    
    /**
     * Name of a graph to put aggregated score to. 
     */
    public static final String AGGREGATED_PUBLISHER_SCORE_GRAPH_URI = NAMESPACE + "aggregatedPublisherScore";
    
    /**
     * Prefix of named graphs where links generated by OI are placed.
     */
    public static final String GENERATED_LINKS_GRAPH_URI_PREFIX = NAMESPACE + "generatedLinks/";
    
    /**
     * Infix of named graph where metadata in the output are stored.
     */
    public static final String QUERY_METADATA_GRAPH_URI_INFIX = "metadata/";
    
    /**
     * Infix of URIs identifying a Quality Assessment rule.
     */
    public static final String QUERY_QA_RULE_URI_INFIX = "QARule/";
    
    /**
     * Infix of URIs of named graph where the result quads are placed.
     */
    public static final String QUERY_RESULT_GRAPH_URI_INFIX = "results/";
}
