DROP TABLE DB.ODCLEANSTORE.QA_RULES_TO_PUBLISHERS_RESTRICTIONS;
DROP TABLE DB.ODCLEANSTORE.QA_RULES;
DROP TABLE DB.ODCLEANSTORE.PUBLISHERS;

CREATE TABLE DB.ODCLEANSTORE.PUBLISHERS
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	uri NVARCHAR(1024) NOT NULL
);

INSERT INTO DB.ODCLEANSTORE.PUBLISHERS VALUES (1, n'http://www.seznam.cz');
INSERT INTO DB.ODCLEANSTORE.PUBLISHERS VALUES (2, n'http://www.google.com');
INSERT INTO DB.ODCLEANSTORE.PUBLISHERS VALUES (3, n'http://www.isvzus.cz');
