DROP TABLE DB.ODCLEANSTORE.QA_RULES_TO_PUBLISHERS_RESTRICTIONS;
DROP TABLE DB.ODCLEANSTORE.QA_RULES;
DROP TABLE DB.ODCLEANSTORE.PUBLISHERS;

CREATE TABLE DB.ODCLEANSTORE.PUBLISHERS
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	label NVARCHAR(255) UNIQUE NOT NULL,
	uri NVARCHAR(1024) NOT NULL
);

INSERT INTO DB.ODCLEANSTORE.PUBLISHERS (label, uri) VALUES (n'Seznam', n'http://www.seznam.cz');
INSERT INTO DB.ODCLEANSTORE.PUBLISHERS (label, uri) VALUES (n'Google', n'http://www.google.com');
INSERT INTO DB.ODCLEANSTORE.PUBLISHERS (label, uri) VALUES (n'IZVUS', n'http://www.isvzus.cz');
