CREATE TABLE DB.ODCLEANSTORE.EN_PIPELINE_RESULTS
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	graphId INTEGER NOT NULL,  
	pipelineId INTEGER NOT NULL,
	pipelineAuthorId INTEGER NULL,
	isExistingGraph SMALLINT NOT NULL DEFAULT 0,
	isSuccess SMALLINT NOT NULL DEFAULT 0,
	errorMessage LONG NVARCHAR NULL,
	created DATETIME,

	FOREIGN KEY (graphId) REFERENCES DB.ODCLEANSTORE.EN_INPUT_GRAPHS(id) ON DELETE CASCADE
);


