ALTER TABLE DB.ODCLEANSTORE.EN_INPUT_GRAPHS ADD namedGraphsPrefix NVARCHAR NOT NULL DEFAULT n'';
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS SET namedGraphsPrefix = n'http://opendata.cz/infrastructure/odcleanstore/';
ALTER TABLE DB.ODCLEANSTORE.EN_INPUT_GRAPHS MODIFY namedGraphsPrefix NVARCHAR NOT NULL;

