ALTER TABLE DB.ODCLEANSTORE.PIPELINES ADD COLUMN authorId INTEGER NULL; 
ALTER TABLE DB.ODCLEANSTORE.PIPELINES ADD FOREIGN KEY (authorId) REFERENCES DB.ODCLEANSTORE.USERS(id) ON DELETE SET NULL;

ALTER TABLE DB.ODCLEANSTORE.QA_RULES_GROUPS ADD COLUMN authorId INTEGER NULL; 
ALTER TABLE DB.ODCLEANSTORE.QA_RULES_GROUPS ADD FOREIGN KEY (authorId) REFERENCES DB.ODCLEANSTORE.USERS(id) ON DELETE SET NULL;

ALTER TABLE DB.ODCLEANSTORE.DN_RULES_GROUPS ADD COLUMN authorId INTEGER NULL; 
ALTER TABLE DB.ODCLEANSTORE.DN_RULES_GROUPS ADD FOREIGN KEY (authorId) REFERENCES DB.ODCLEANSTORE.USERS(id) ON DELETE SET NULL;

ALTER TABLE DB.ODCLEANSTORE.OI_RULES_GROUPS ADD COLUMN authorId INTEGER NULL; 
ALTER TABLE DB.ODCLEANSTORE.OI_RULES_GROUPS ADD FOREIGN KEY (authorId) REFERENCES DB.ODCLEANSTORE.USERS(id) ON DELETE SET NULL;

ALTER TABLE DB.ODCLEANSTORE.ONTOLOGIES ADD COLUMN authorId INTEGER NULL; 
ALTER TABLE DB.ODCLEANSTORE.ONTOLOGIES ADD FOREIGN KEY (authorId) REFERENCES DB.ODCLEANSTORE.USERS(id) ON DELETE SET NULL;CREATE TABLE DB.ODCLEANSTORE.RELATION_TYPES
(
  id INTEGER NOT NULL IDENTITY PRIMARY KEY,
  uri NVARCHAR(1024) UNIQUE NOT NULL
);

DELETE FROM DB.ODCLEANSTORE.RELATION_TYPES;

INSERT INTO DB.ODCLEANSTORE.RELATION_TYPES (uri) VALUES (n'http://www.w3.org/2002/07/owl#sameAs');
INSERT INTO DB.ODCLEANSTORE.RELATION_TYPES (uri) VALUES (n'http://www.w3.org/2002/07/owl#equivalentProperty');
INSERT INTO DB.ODCLEANSTORE.RELATION_TYPES (uri) VALUES (n'http://www.w3.org/2000/01/rdf-schema#subClassOf');
INSERT INTO DB.ODCLEANSTORE.RELATION_TYPES (uri) VALUES (n'http://www.w3.org/2000/01/rdf-schema#subPropertyOf');


ALTER TABLE DB.ODCLEANSTORE.DN_RULE_COMPONENT_TYPES DROP CONSTRAINT labelCheck;
ALTER TABLE DB.ODCLEANSTORE.DN_RULE_COMPONENT_TYPES ADD CONSTRAINT labelCheck CHECK (label IN ('INSERT', 'DELETE', 'MODIFY'));
INSERT INTO DB.ODCLEANSTORE.DN_RULE_COMPONENT_TYPES (id, label) VALUES (2, 'MODIFY');


ALTER TABLE DB.ODCLEANSTORE.EN_ATTACHED_ENGINES
ADD
	isPipelineError SMALLINT NOT NULL,
	isNotifyRequired SMALLINT NOT NULL,
	stateDescription NVARCHAR(255);

ALTER TABLE DB.ODCLEANSTORE.QA_RULES_GROUPS ADD COLUMN isUncommitted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE DB.ODCLEANSTORE.DN_RULES_GROUPS ADD COLUMN isUncommitted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE DB.ODCLEANSTORE.OI_RULES_GROUPS ADD COLUMN isUncommitted SMALLINT NOT NULL DEFAULT 0;

CREATE TABLE DB.ODCLEANSTORE.QA_RULES_UNCOMMITTED
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	groupId INTEGER NOT NULL,
	filter LONG NVARCHAR NOT NULL,
	coefficient REAL NOT NULL,
	description LONG NVARCHAR,
	
	FOREIGN KEY (groupId) REFERENCES DB.ODCLEANSTORE.QA_RULES_GROUPS(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	groupId INTEGER NOT NULL,
	description LONG NVARCHAR,
	
	FOREIGN KEY (groupId) REFERENCES DB.ODCLEANSTORE.DN_RULES_GROUPS(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.DN_RULE_COMPONENTS_UNCOMMITTED
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	ruleId INTEGER NOT NULL,
	typeId INTEGER NOT NULL,
	modification LONG NVARCHAR NOT NULL,
	description LONG NVARCHAR,
	
	FOREIGN KEY (ruleId) REFERENCES DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED(id) ON DELETE CASCADE,
	FOREIGN KEY (typeId) REFERENCES DB.ODCLEANSTORE.DN_RULE_COMPONENT_TYPES(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.OI_RULES_UNCOMMITTED
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	groupId INTEGER NOT NULL,
	label NVARCHAR(255) NOT NULL,
	linkType NVARCHAR(255) NOT NULL,
	sourceRestriction NVARCHAR(255),
	targetRestriction NVARCHAR(255),
	linkageRule LONG NVARCHAR NOT NULL,
	filterThreshold DECIMAL,
	filterLimit INTEGER, 
	
	FOREIGN KEY (groupId) REFERENCES DB.ODCLEANSTORE.OI_RULES_GROUPS(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.OI_OUTPUTS_UNCOMMITTED
(
	id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	ruleId INTEGER NOT NULL,
	outputTypeId INTEGER NOT NULL,
	minConfidence DECIMAL,
	maxConfidence DECIMAL,
	fileName VARCHAR(255),
	fileFormatId INTEGER,

	FOREIGN KEY (ruleId) REFERENCES DB.ODCLEANSTORE.OI_RULES_UNCOMMITTED(id) ON DELETE CASCADE,
	FOREIGN KEY (outputTypeId) REFERENCES DB.ODCLEANSTORE.OI_OUTPUT_TYPES(id) ON DELETE CASCADE,
	FOREIGN KEY (fileFormatId) REFERENCES DB.ODCLEANSTORE.OI_FILE_FORMATS(id) ON DELETE CASCADE
);


INSERT INTO DB.ODCLEANSTORE.QA_RULES_UNCOMMITTED SELECT * FROM DB.ODCLEANSTORE.QA_RULES;
INSERT INTO DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED SELECT * FROM DB.ODCLEANSTORE.DN_RULES;
INSERT INTO DB.ODCLEANSTORE.DN_RULE_COMPONENTS_UNCOMMITTED SELECT * FROM DB.ODCLEANSTORE.DN_RULE_COMPONENTS;
INSERT INTO DB.ODCLEANSTORE.OI_RULES_UNCOMMITTED SELECT * FROM DB.ODCLEANSTORE.OI_RULES;
INSERT INTO DB.ODCLEANSTORE.OI_OUTPUTS_UNCOMMITTED SELECT * FROM DB.ODCLEANSTORE.OI_OUTPUTS;


CREATE TABLE DB.ODCLEANSTORE.DN_REPLACE_TEMPLATE_INSTANCES
(
  id INTEGER NOT NULL IDENTITY PRIMARY KEY,
  groupId INTEGER NOT NULL,
  rawRuleId INTEGER NOT NULL,
  propertyName NVARCHAR(255) NOT NULL,
  pattern NVARCHAR(255) NOT NULL,
  replacement NVARCHAR(255) NOT NULL,

  FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.DN_RENAME_TEMPLATE_INSTANCES
(
  id INTEGER NOT NULL IDENTITY PRIMARY KEY,
  groupId INTEGER NOT NULL,
  rawRuleId INTEGER NOT NULL,
  sourcePropertyName NVARCHAR(255) NOT NULL,
  targetPropertyName NVARCHAR(255) NOT NULL,

  FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES(id) ON DELETE CASCADE
);

CREATE TABLE DB.ODCLEANSTORE.DN_FILTER_TEMPLATE_INSTANCES
(
  id INTEGER NOT NULL IDENTITY PRIMARY KEY,
  groupId INTEGER NOT NULL,
  rawRuleId INTEGER NOT NULL,
  propertyName NVARCHAR(255) NOT NULL,
  pattern NVARCHAR(255) NOT NULL,
  keep SMALLINT NOT NULL DEFAULT 1,

  FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES(id) ON DELETE CASCADE
);


ALTER TABLE DB.ODCLEANSTORE.DN_REPLACE_TEMPLATE_INSTANCES DROP CONSTRAINT DN_REPLACE_TEMPLATE_INSTANCES_DN_RULES_rawRuleId_id;
ALTER TABLE DB.ODCLEANSTORE.DN_REPLACE_TEMPLATE_INSTANCES ADD FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED(id) ON DELETE CASCADE;

ALTER TABLE DB.ODCLEANSTORE.DN_FILTER_TEMPLATE_INSTANCES DROP CONSTRAINT DN_FILTER_TEMPLATE_INSTANCES_DN_RULES_rawRuleId_id;
ALTER TABLE DB.ODCLEANSTORE.DN_FILTER_TEMPLATE_INSTANCES ADD FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED(id) ON DELETE CASCADE;

ALTER TABLE DB.ODCLEANSTORE.DN_RENAME_TEMPLATE_INSTANCES DROP CONSTRAINT DN_RENAME_TEMPLATE_INSTANCES_DN_RULES_rawRuleId_id;
ALTER TABLE DB.ODCLEANSTORE.DN_RENAME_TEMPLATE_INSTANCES ADD FOREIGN KEY (rawRuleId) REFERENCES DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED(id) ON DELETE CASCADE;


ALTER TABLE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES ADD COLUMN canResetPipeline SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE DB.ODCLEANSTORE.EN_INPUT_GRAPHS ADD COLUMN resetPipelineRequest SMALLINT NOT NULL DEFAULT 0;

UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 1;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 2;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 1  WHERE id = 3;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 4;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 1  WHERE id = 5;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 1  WHERE id = 6;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 7;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 8;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 9;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 10;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 11;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET canResetPipeline = 0  WHERE id = 12;

INSERT INTO DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES (id, label, canResetPipeline) VALUES (13, n'FINISHEDINDIRTY', 1);
INSERT INTO DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES (id, label, canResetPipeline) VALUES (14, n'REMOVEDOLDGRAPH', 1);


INSERT INTO DB.ODCLEANSTORE.EN_PIPELINE_ERROR_TYPES (id, label, description) VALUES (3, n'COPY_TO_CLEAN_DB_FAILURE', n'A failure during data copying from dirty to clean database.');



UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET label = n'OLDGRAPHSPREFIXED' WHERE id = 13;
UPDATE DB.ODCLEANSTORE.EN_INPUT_GRAPHS_STATES SET label = n'NEWGRAPHSPREPARED' WHERE id = 14;



