ALTER TABLE DB.ODCLEANSTORE.ONTOLOGIES ADD definition LONG NVARCHAR;

ALTER TABLE DB.ODCLEANSTORE.OI_RULES ADD description LONG NVARCHAR;
ALTER TABLE DB.ODCLEANSTORE.OI_RULES_UNCOMMITTED ADD description LONG NVARCHAR;

ALTER TABLE DB.ODCLEANSTORE.QA_RULES ADD label NVARCHAR(255) NOT NULL DEFAULT n'';
ALTER TABLE DB.ODCLEANSTORE.QA_RULES_UNCOMMITTED ADD label NVARCHAR(255) NOT NULL DEFAULT n'';
ALTER TABLE DB.ODCLEANSTORE.DN_RULES ADD label NVARCHAR(255) NOT NULL DEFAULT n'';
ALTER TABLE DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED ADD label NVARCHAR(255) NOT NULL DEFAULT n'';

UPDATE DB.ODCLEANSTORE.QA_RULES SET label = COALESCE(description, '');
UPDATE DB.ODCLEANSTORE.QA_RULES_UNCOMMITTED SET label = COALESCE(description, '');
UPDATE DB.ODCLEANSTORE.DN_RULES SET label = COALESCE(description, '');
UPDATE DB.ODCLEANSTORE.DN_RULES_UNCOMMITTED SET label = COALESCE(description, '');

